name: trallo
services:
- name: web
  source_dir: /
  github:
    repo: chrishaines/trallo
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXT_PUBLIC_SUPABASE_URL
    scope: RUN_TIME
    type: SECRET
  - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
    scope: RUN_TIME
    type: SECRET